# Generated by Django 5.0.7 on 2024-11-11 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_reviews_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='projects.project'),
        ),
    ]
