# Generated by Django 5.0.7 on 2024-11-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_reviews_project'),
        ('users', '0004_profile_social_stackoverflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
